version: '3'
services:
  app:
    container_name: go-anki
    image: golang
    volumes:
      - ../:/srv/
      - ~/go:/go
    environment:
      - TZ=Asia/Tokyo
    tty: true
    command: bash
    working_dir: /srv
    links:
      - proxy
  proxy:
    image: dperson/torproxy

