version: '3'
services:
  app:
    container_name: go-anki
    image: library/golang:1.8
    volumes:
      - ../:/srv/
      - ~/go:/go
    env_file: .env
    tty: true
    working_dir: /srv
    links:
      - proxy
  proxy:
    image: dperson/torproxy

