name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.x'
      - run: env | sort

      - run: make lint
      - run: make test
      - name: Build
        run: |
          go build cmd/server/main.go
